export const CREATE_COURSE = "CREATE_COURSE"
export const EDIT_COURSE = "EDIT_COURSE"

export const SEARCH_COURSES = "SEARCH_COURSES"
export const FETCH_COURSES_SUCCEED = "FETCH_COURSES_SUCCEED"
export const DELETE_COURSE_SUCCEED = "DELETE_COURSE_SUCCEED"